const data = [
	{word: "abac", definition: "(ABAC/ABAK) Meaning: (pp.) The time of the day, from dawntill noon. Bucas abac, tomorrow morning; bucas cayabacan, early tomorrow; bucas	caya-yabacan, (superlative of Ca),tomorrow at the earliest hour of themorning. Active verb: to eat lunch (which to the natives is 9 to 10 A.M.), to eat at such an hour is called capamanabac, caindicates a fixed time in the morning. It admits several suppositions, as in manabacayo, to lunch together; it can connote literal relationships, manabac ca careang caponmo, you take lunch with your family/friends; manabac-nabac, to eat here, or eat there on the same morning; and also that which takes place throughout the mornings, like, buying or selling. P. 1. and 3. what is eaten at such an hour. Also, with the same variations, it means to do something in the morning v.g. Inabacanco ingpamanğaloco, I began to work or have worked from the morning, / Pepabacan moco, & Note that Manabac, in this second sense, is to work v.g, only in the morning, and not through the afternoon."},
    {word: "abak", definition: "(ABAC/ABAK) Meaning: (pp.) The time of the day, from dawn till noon. Bucas abac, tomorrow morning; bucas cayabacan, early tomorrow; bucas caya-yabacan, (superlative of Ca), tomorrow at the earliest hour of the morning. Active verb: to eat lunch (which to the natives is 9 to 10 A.M.), to eat at such an hour is called capamanabac, ca indicates a fixed time in the morning. It admits several suppositions, as in manabacayo, to lunch together; it can connote literal relationships, manabac ca careang caponmo, you take lunch with your family/friends; manabac-nabac, to eat here, or eat there on the same morning; and also that which takes place throughout the mornings, like, buying or selling. P. 1. and 3. what is eaten at such an hour. Also, with the same variations, it means to do something in the morning v.g. Inabacanco ingpamanğaloco, I began to work or have worked from the morning, / Pepabacan moco, & Note that Manabac, in this second sense, is to work v.g, only in the morning, and not through the afternoon."},
	{word: "abagat", definition: "(ABAGAT) Meaning: (pp). Noun. Violent wind coming from the sea. Abagatan, the South, or wind coming from south; by the suffix an, of Chap 13. "},
	{word: "abias", definition: "(ABIAS/ABYAS) Meaning: (pp.) Noun, milled rice, unhulled rice. Active verb and its more frequently used infinitive, manabias, to remove the hull or clean the rice, to turn the palay into abias. P.3, past, Inabiasan, palay milled or ground / pounded into abias."},
    {word: "abyas", definition: "(ABYAS/ABIAS) Meaning: (pp.) Noun, milled rice, unhulled rice. Active verb and its more frequently used infinitive, manabias, to remove the hull or clean the rice, to turn the palay into abias. P.3, past, Inabiasan, palay milled or ground / pounded into abias."},
	{word: "abit", definition: "(ABIT) Meaning: Noun, Strong pull, as, in pulling the ears. Active verb and its infinitive, manabit, to stretch, as in stretching clothes, a cord or any other thing, like, in the  rowing a boat. P.2 past, Inabitan, that which is stretched/pulled. Mi maibitan, with a compansion. Abit-abitan, to pull or stretch lightly. See Chap. 17 ( Grammar, Bergaño)."},
	{word: "babad", definition: "(BABAD) Meaning: (pp.) That this is pronounced with an accent, produced by the N. Adjective (which is the adjective from the root) the soaked thing or wet object: active voice, which in its conjugation, the active is Bababad, minabad, mabad, to soak purposely (and if not intransitive, there will be a mark as a Neutral verb.) P. 1. in this Passive which is the present, Ibababad, binabad, ibabad, that which is soaked. Passive 3. it is bababaran, bebaran, babaran, and means the thing soaked, not dipped into the water, but soaked superficially). Neutral verb of Ma, (there are also neutral verbs of Mi), Mabababad, that which is actually soaked, or remaining soaked; mebabad, what wasoaked, mababad, what is yet to be soaked; there may be other marks in the rest of the infinitive, besides what I have explained. Oleum et operam perdidi, either I am confused, or you are stupid. N. S. is substative noun, N. Adject., adjectival noun"},
	{word: "babâ", definition: "(BABÁ) Meaning: (g.) Noun, the chin, not the beard."},
	{word: "baba", definition: "(BABA) Meaning: (a. and g.) Neutral verb, Bababâ, mebâ, mabâ, to go down, descend; paybaba, to go down on its own or purposely, or lower. P. 1. Past: Beba, what is lowered, v. g. a lamp. Neutral of Ma, to become thus; mababa, adjective, low; if to the passive, and verb of Ma, you add lub, it will mean, lower the self, to be humble: mababalub, humble; pacumbaba, or, paycumbaba, is to go down morally, to become humble, to humble oneself or be contrite; cababan, lowness with lub, humility / humbleness; transitive verb, to lower something physically, physical lowness. Mi, neutral, like that of Ma: emibaba, potential, opposite of Atas, emitas."},
	{word: "bacâs", definition: "(BACÁS) Meaning:  (corrid.) Noun, track, footprint, mark left behind, trace. Active verb, a construction rarely used. Mamacas, memacas, to look for a trace, leave a mark or trace, one who has passed by, or trace of liquor in a cup. Passive, pamacasan, pemacasan, one followed its track, or the place where traces were left behind. Passive, simple: 1. past, Becas, one to whom the mark or trace is shown , that with which a trace is made, like a vestige, or a seal. P. 2. Becasan, the one followed by a trace or mark; P. 3. Becasanan, the place where the mark or trace is made, Becasanan me iting dalan, you left a mark on this road, ining sulliao, on this cup. Also, dalagangalan bacás, & Virgen alan bacásbacás, unblemished maiden, a virgin inviolate, like a cup in which not the least trace of the liquor that I drank remains. Alan bacás casalanan, no stain of sin, Most Blessed Virgin Mary."},
	{word: "bacting", definition: "(BACTING) Meaning: (pp.) Norm, a small bell. Active verb, to ring such a bell. P. 1. the small bell, or for whom it is rung, and why it is rung."},
	{word: "caban", definition: "(CABAN) Meaning: (a.) Norm, a box or chest. And the caban.tthe measure) Active verb, future, caban, mamaban, to place in a chest, ark, or to measure by the caban. Infinitive: Acaban, (ycaban, ?) for both meanings. P. 3. Quebanan, the thing measured by the caban."},
	{word: "calabcab", definition: "CALABCAB) Meaning: (pp.) Noun, the blaze of fire. Neutral verb and that of Mi, to be set ablaze. Mi with an, the one caught by the blaze."},
	{word: "cabira", definition: "(CABIRA) Meaning:  (pp.) Emagcacabira, that which hardly has any importance, or value"},
	{word: "cabud", definition: "(CABUD) Meaning: (a.) Adverb, once, upon the moment, at sight, just as, v. g. Antina cabud queta, it is just like that. Active verb, future, cabud, to work, to be, to become, to work with punctuality. P. 3. The thing in which one is punctual. Infinitive: manğabudya, he is very punctual. Micacabud, micabud, neutral verb, become punctual, v. g. If you are invited to a dinner at 12:00 noon, and you come at 11:00 A.M. they will tell you, Micabudca, you are punctual, much early before dinner time. Cabud, at the moment arriving in-time and before time, all is punctuality. And from this, Cabud ya mabalatong ing tarn, cabud ta calinguan ing daraptanta, cabud ta malilo. It is already understood. (Once a man makes a mistake, at that moment we forget what we are doing, we at once get confused /get ill-willed)."},
	{word: "cascas", definition: "(CASCAS) Meaning:  (pp.) Active verb and its infinitive, cumacas. mansacas. to grate, to rub off, or scrape a seed or bread against the grater,a stone, or a fragment of earthenware.; and therefore, that which is P. 1, is the grater; and Pi and an is the place where in, if the grater, stone is scraped against the medicine, seed, bread; the grater, the stone, and the bread etc., is the P. 2. past tense, Quinacas or quecasan, and also the scrapings; Mi, transitive, Mi, passive., Picacasan, the fragments, and also the seed from which they were scraped. Ma, neutral, to become grated or scraped. Maca, potential."},
	{word: "daclut", definition: "(DACLUT) Meaning: Active verb and its infinitive, Mañyaclut, to get/take by handful, with one hand or both, like, cooked rice. P.2. past, diclut, that which is taken/scooped up thus. Ma, neutral, become scooped. Caraclut, one handful, or one take. Caraclutan, that which is taken by the handful. See Damput."},
	{word: "dacdac", definition: "(DACDAC) Meaning: (pp.) Active verb, future, Dacdác, and its infinitive, manvacdac. to drive a stake with the point to the ground. P.1. past, dicdac,that which is driven in to the ground. Mi, transitive, Mi, passitive. Pi and an, the place. Maca, become driven into the ground. Madacdac, abundanceof stakes. See Tulos"},
	{word: "dacap", definition: "(DACAP) Meaning: (a.) Adjective, taken captive, prisoner, o r o ne w h o is in prison. Active verb, future, Dacap\ another construct, Máñyacap, to catch , to capture. P. 1. the motive, or with what. P. 2. Dacpán, syncope , past tense, decap, one who is apprehended , captured. Ma, neutral; manga, if many, become captured, caught, etc."},
	{word: "dagus", definition: "(DAGUS) Meaning: (pp.) Neutral verb, dumasus. and that of Mi, to slide down. See Dag-glus. P. 1. that which slides down, like, downhill,"},
	{word: "daya", definition: "Meaning: (pp.) Noun, blood. Neutral verb, dumava. to bleed. Pa, to cause to bleed, like, by a knife. Maraya, meraya, bleed abundantly, like, due to lashings. Misangdaya, or, micaraya, they are all Pampangos (have the same blood). Carayaraca, says one Pampango to another, even if they are not relatives, which is the same as saying, we are of one nation. Micaraya cata, Misangdayacata, carayaraca, you are of my nation, my countryman; You are proud, Pablasang daya cang Capampangan, for you belong to the Pampango nation. Ing dayang Castila, the Spanish nation. Detang dayang deta, those nations. Matas a daya, is of noble blood. Malutu cu mo dayang anti queca, I am as noble as you are. Mababa, o matuling a daya, of vile blood. Gagalao a raya, guinalao a raya, is said when one becomes angry in defending his blood or race, his blood stirs, also, blood boils even without fire."},
	{word: "ebon", definition: "(EBON) Meaning: (pp.) Noun, egg of fowls, suckling of quadrupeds, like cows, sheep, etc. Ebunan, one that has eggs. Verb: Manğebon, to lay eggs, or to have a suckling. Panğebonan, nest of eggs. Pipangaebonan, or pipánsebonán, the same."},
	{word: "ebus", definition: "Meaning: .(p p.) Noun, the wild palm of burr, medicine against bótete, a kind of mosquito"},
	{word: "eran", definition: "Meaning:  (pp.) Stairs or ladder, like those of a house."},
	{word: "eyata", definition: "(EYATA) Meaning: (pc.) Adverb, to start a clause, like enimin Latin, For, therefore, hence, wherefore, for that reason, etc."},
	{word: "gabac", definition: "(GABAC) Meaning: (a.) Adjective, a thing tom, ripped, like cloth. Active verb and its infinitive, eumabac. mansabac. to tear. P. 2. past, Guinabac, that which was tom."},
	{word: "gagad", definition: "(GAGAD) Meaning: (pp.) Neutral verb, go for more, go further, like anger for the irritated, the appetite for what is forbidden, questions or laws for the offended, a crowd for one who has for the few. P. 1. the one who, that which, Guegad. P. 3. past, Guegaran, to whom. To say “Guegaran” to mean “to imitate”, would be Tagalizing it. See Dagdag. ."},
	{word: "galamay", definition: "Meaning: The legs of the crab."},
	{word: "galang", definition: "(GALANG) Meaning: (pp.) noun, Honor, respect, veneration, reverence like that which is due to God, to ones parents, or elders, superiors. Active verb, zurnalarz, izalanz. to honor, or respect thus. P. 1. to whom. Ibpang igagalang. Reverend Father. Cagalanggalangan a Ibpa, My Most Reverend Father, the superlative of the verbal Ca. Migalang, two honoring one another. Magalang, respectful, with abundant respect, courteous honorer. Also, a bracelet; Maggalang, to wear a bracelet. Also, a clamp, clasp, a bond. (Galanz zalanz. biscuits in the form of bracelets.)"},
	{word: "galasgas", definition: "(GALASGAS) Meaning: (pp.) Fluency in talking or reading aloud, fast talker/ fast reader. Magalasgas yang anac iti. This child is brilliant, lively, genious, prompt, expeditious, speaks fluently. Cagalasgasan, abstract."},
	{word: "gaga", definition: "(GAGA) Meaning: GAGA, (g.) Noun, Fray, quarrel, angry reprimand, chirp of a bird, or howling of an animal, not as strong as gacgac. Active verb and its infinitive, sumasa. manğasa. to act/behave in this manner. P. 1. the motive. P. 3. past, Guegan, object of the quarrel. Mi, with company, with its predicates."},
	{word: "gayac", definition: "(GAYAC) Meaning: GAYAC. (pp.) Noun, Arrangement or preparation of things for a trip or departure. Verb, savac, isavac. to prepare things for a trip. P. 1. past, Gueyac, one who prepares for a trip on behalf of another, or for whom. Mi, with company. Maca, become ready, prepared, or expedited. Neutral verb and active, and its infinitive, to prepare oneself, to get ready, to become disposed."},
	{word: "ibpa", definition: "(IBPA) Meaning: (pp.) Noun, father, and also a word of endearment. Pa, be called a father. Paibpan da co, they call me Father, or refer to me as Father. See Mi, correlatives: Mi-ibpa, the father and son."},
	{word: "igut", definition: "(IGUT) Meaning:  (p p .) Active verb a n d its infinitive , misut. manisut. to pull harder what one is already pulling , but it is necessary to pull it further to make it tauter, or eliminate whatever looseness there still might be. Maigut, adjective , strained ; in idiomatic usage: the miserable."},
	{word: " iyac", definition: "(IYAC) Meaning: (pp)  Noun , a cry. Active verb , cumiac, to cry. P. 1. the motive . P. 3. to whom . Micaquiac, the criers, like cry in g children."},
	{word: " iyias", definition: "(IYIAS) Meaning: (p p .) Noun , jewels . Mag, or, malyias, to wear them . Pa, to give them . P. 3. to whom."},
	{word: " iyas", definition: "(IYAS) Meaning: (p p .) Noun , jewels . Mag, or, malyias, to wear them . Pa, to give them . P. 3. to whom."},
	{word: "ibay", definition: "(IBAY) Meaning: (dipht.) Maybay, meybay, to become giddy, or faint, become intoxicated for chewing betel nut. Melaybay, close to becoming intoxicated thus. Pangaybay."},
	{word: "inang", definition: "(INANG) Meaning: (pp.) Active verb and its infinitive, maninang. to solder metals. P. 1. and P. 2. that which is soldered. Maca, is soldered, become soldered. Mi, transitive; Mi, passive. Piinangan,piinang, passive ,with company. Pi and an, the juncture, the point soldered."},
	{word: "iyi", definition: "(IYI) Meaning: (pp) Noun , urine . Active verb and its infinitive.mzv/, to urinate. (Mimiyi, Miniyi, miyi, o r mimi, mini, mi). P. 2. the place, Pi, and an, (Piiyian) the urinal/the bed - pan , chamber pot. Palyi, frequently urinating, habitual bed-wetter/bed-wetting."},
	{word: " ilag", definition: "(ILAG) Meaning: (p p .) Neutral verb , milas. minias, to draw oneself aside, or withdraw the  body away from something g . P. 1. the motive. P. 3. from where , or from  whom."},
	{word: "yabyab", definition: "(YABYAB) Meaning: (pp) Noun , urine . Active verb and its infinitive.mzv/, to urinate. (Mimiyi, Miniyi, miyi, o r mimi, mini, mi). P. 2. the place, Pi, and an, (Piiyian) the urinal/the bed - pan , chamber pot. Palyi, frequently urinating, habitual bed-wetter/bed-wetting."},
	{word: "yaman", definition: "(YAMAN) Meaning:  (pp.) Noun, deliciousness, tastiness. Maniaman, delicious. Maniaman quing lub co, morally, with all my heart, in all willingness. Maniaman a lub, determined and willing. Neutral verb, yayaman, inaman, yumaman, and that of Ma, to become very delicious, delightful to the taste, very pleasant. P. 3. Caniamanan, quiniamanan, not the object, but the person enjoying the pleasure/pleasantness. Irony: Ba! Quiniamanan ca? Said to one who breaks his head! Caniamanana, like casampatan na. Maca, causal. P. 2. Yayamanan, inamanan. Inaman, one who has tasted and coom to be pleased with it. v.g. Ding Santos yayamanan da quing lub da ing casaquitan, and also, picacaniamanan, past, picaniamanan. Ma, of appraising the savor, Mimamaniaman, pleasant to the taste, to the touch."},
	{word: "yugyog", definition: "YUGYOG) Meaning:  (pp.) Active verb and its infinitive, Manugyug, to shake up and down, like a trotting horse, or a branch to make its fruits fall. P. 1. & P. 2. that which is shaken, is said of a worn-out horse, which go shaking the rider up and down, or of the rider that allows this to happen."},
	{word: "yumu", definition: "(YUMU) Meaning:  (pc.) Noun, sweetness. Neutral verb and that of Ma, to become sweet. P. 3. of Ca, like caniamanan, cayumuan, queyumuan. Mayumu, adjective, sweet. lea máMaca, the cause. Cayumuyumuan, superlative, sweetest."},
	{word: "labas", definition: "(LABAS) Meaning: (pp.) Neutral verb and its infinitive, to pass; and that of Mi, is said also about the passage of time/time passing bu. P.1. what is carried in passing, Mi, transitive; Mi,passive. P.3. past,Lebasan, the place, or the time that one had passed. Mi with an, the place, or the time passed. Also, Quelabsan quisap, an instant, at the blink of an eye, Quelabsanmema, the time it took to chew maman,quelabsan Bapu Maria the time it look to say a Hail Mary. Also, Palabasan, what is let to pass. Materially and formally==Mengamanuyauariquing pepalabasan, like when one speaks with a certain servant, or his freed slave; this is its sense:the reason for this is a long history: if you want me to tell you, you have to pay me a fee. Pepalabasan mo couari?"},
	{word: "labac", definition: "(LABAC) Meaning: (pp.) NOUN, Puddle, water hole.Labac labac, to have many puddles, as in the aftermath of a heavy shower. Ma labac,the soil/earth becoming full of these holes, or the sunken face of  a person who no longer has molars, with its in finitive, Manga labac. Active verb, future, Labac, and its infinitive, to make holes, like on the ground, or on a piece of wood, badly planed. P.3, the place, past, Lebacan."},
	{word: "labi", definition: "(LABI) Meaning: (g.) Noun, lip, including the lip/lid of a jar. Malabi, thick lipped ."},
	{word: "lablab", definition: "(LABLAB) Meaning: (pp.) Noun, flame. Mi, neutral, the aflamed, burning brightly Palablaban, the fire. Also, active verb, manlablab. the way a pig eats, and applied deridingly to people. Lablab ca, Go on, devour/swallow, you glutton."},
	{word: "lacuan", definition: "Meaning: (pp.) Irregular passive. Lalacuan, licúan, lacuan, to leave behind; infinitive, Manlacuan, act. P. 3. Who is left behind. Lacuanan, and in its tense, Lacuananan, the passive of the variation: Panlacuan, the thing left behind /abandoned. Malacuan, become left behind. See Lacao."},
	{word: "magas", definition: "(MAGAS) Meaning: (pp.) Verb: Manimagas, menimagas, one who is already eating the dessert, (which shoud be eaten last), dessert is panigamas, (panimaeas). P. 1. like sweet preserves."},
	{word: "magurung", definition: "(MAGURUNG) Meaning: (pp.) Mid-day, half-day, from morning till noon. Mecaduan magurung, a day and a half. Past, Megurung, Nun teng depat mung megurung? Where is now the work you did in a half day? Pagurungan, pepagurungan. What was done in a half-day. Pagurungan dañé bucos, tomorrow till noon, they shall finish it. Contrary to this: pangatpanapunan, what is done in the whole afternoon (from noon till sundown). See Gatpanapon. Mamenği, what is done at night time. See Bengi. "},
	{word: "mal", definition: "(MAL) Meaning:  Adjective, Precious, formally, and materially, for merchandise: costly, dear. Neutral verb, Cacamal, qüinamal, carnal, and that of Mi, become precious, become costly/dear. P. 1. Imamal, mimal, imal, or, Icacamal, quemal, icamal, the thing made precious, or raised in price. Mi, transitive; Mi, passive, ofImal, mimamal, mimal, the same as Mi, passive, transitive of Icamal, micacamal, micamal, and its same passive of Mi, and Ca, of the first. Icamal, quemal. Maca, macacamal, mecacamal; Carnal, abstract, and Camalan also, like Pali, capalian. Macamal, of abundance: precious, or dear. Magcamal, with intent, make precious. P. 1. Pagcamal, pigcamal, the motive. P. 3. the objective. Pa, to call it precious, and from this, to hold it precious, dear, in the s manner of pacalulu; pacamalan, pepacamalan, the one held dear/precious by the passive 1. Ipacamal, the motive, or that with which, and at times, the subject, and therefore it is to make it to happen, from among the poor. Gueudnen mal ning Ari: that is, Pepacamalane ningAri, The King made him dear, the King held him in high esteem; but Geua neng macamal ning Ari, The King made him a noble, awarded him with nobility. Mal a mal, very, very precious, or dear. Macamal a macamal, precious, but not dear."},
	{word: "malun", definition: "(MALUN) Meaning: (a .) Noun , grief, repentance , regret. Magmalim, with company. Bitquil, is also said of material things / physical pains, like that of the arm , which is sore , or painful to due carrying big , or prolonged burdens. M ebitquil ya."},
	{word: "mana", definition: "(MANA) Meaning: MANA, (pp.) Noun, inheritance. P. 2. future, Manam, past, menan; present, mamanan, that which is inherited. Mi, mimana, to come upon an inheritance. Mimamana, mimana, to inherit. P. 3. Pimamanan, pimanan, from whom. Mica, of immmtnceMicamana, like micabunga, shall have an inheritance. Mi, with company, with all its variations P. 2. to say inherit equally, add, Sang: misangmana, manialimana, lookup their frequentative infinitive!"},
	{word: "misan", definition: "(MISAN) Meaning (pp.) Adverb, One time, once upon a time, or on one occasion, Manaral ya misan, he was preaching at one time, Manaral ya minsan aldao, misan naman, at least once a day. Misan pa, once more, one more time. Mamisanmisan, occasionally, like, now, the good, and then, the bad. Pamisanan, R 2. place things together in one place. Macapamisan, being together in one place. Mi (mipamisan) with company, with its variation, manga, and with its R 2. Pi and an, (pipamisanan, pimisanan), the place."},
	{word: "nabang", definition: "(NABANG) Meaning: (pp.) or, Paquinabang, advantage, gain, or fruit derived, shared, or produced from another thing. Active verb, numabans. by necessity, is the Maqui (sharing), Maquinabang, mequinabang. P. 3. Nabangan, or, nabangnan. Paquinabangan, or Paquinabangnan, from whom it is shared, and that of the simple root, when it refers or relates over the gains / good which it possesses, v. g. Nabangan co ing gracia, or, ing tula banua, precinds that it is shared or participated in, and this good is Nabang. The Paqui, always entails a relation of partaking/sharing, and the good inasmuch as it is participated in, is Paquinabang. Note, that one and the same thing, inasmuch as it is a cause, is the Passive 3, ‘ And inasmuch it is an effect, it is Nabang. Like Grace, inasmuch as it is the effect of the sacraments, it is Nabang, and it is Paquinabang as a casue of our becoming children of God, and it is broad/extensive P. 3. And thus, from cause to effect, until it stops in God, the First Cause of all good. Mi, with company; Mi, paquinabang, those who share one with the others, like in the Communion of Saints. The companion, Capaquinabang:talapaquinabang, is distributive. It means each one shares, v. g. as from a pile, or bank. Mituluquinabang, is also with company, but it only says that they are cosharers, not one sharing to another (adinvicem). Pituluquinabangan, P. 2.pitoloquinabang, the pile from which. Also, with Nabang, it is to cause it to enjoy; with Paquinabang, to cause it to share. P. 1. Inabang, (not more) that which is made useful."},
	{word: "Nabo", definition: "(NABO) Meaning: (pp.) Active verb, inabo. and its infinitive, Mangnabo, to throw down, to throw from above. P. 1. past, Nibu, that which. P. 3. past, Nibuan, the place. Mi, transitive; Mi, passive. Pi, and an. Neutral verb of Ma, manga, with an, or without an. Ca, and an, P. 3. where in/on. From this, Nanung canabuan nal What does it mean? Or, What would it mean. Nabonabo, frequentative."},
	{word: "napnap", definition: "(NAPNAP) Meaning: (pp.) Active verb and its infinitive , Magnapnap, gather all, leaving nothing , and from this, leave it clean , and form ally, catch everything , or consider everything , leaving nothing out. P. 1. that with which; P. 2. p ast, Nipnap, that which is exhausted. Ma, neutral, become taken wholly thus. Manapnap yang tauo, of one who looks at everything , and looks again , without leaving  anything unconsidered , even the m in u test detail. From this, it is said, clean someone of everything he has. Pignapnap daco, or nipnap da cong penacauanan. They did not leave me anything, they stole everything from me. Mipangnapnap cata, is said of two playing to the end , v. g. up to everything one has, is Mi, with company. P. 3.: the winning card in a four-of-a-kind card game, v. g. To whom it is thrown ."},
	{word: "nangnang", definition: "(NANGNANG) Meaning: (pp.) Active verb, future, and its infinitive , Numangnang, or magnangnang / manyangnang. to broil, like a chicken . Passive 1, past, Ningnang, that which is broiled, or appliquéd , like a cloth . Maca , become broiled .Pinangnanğan, Pi, and an, Ma, neutral, and manga, without an. Idiomatically , Manangnangpa, it is still soft, it needs to be cooked over low fire . Magpacanangnang ca, go slowly in what you have to resolve. Pagpacanangnanğan, the thing that is slowly resolved."},
	{word: "nasi", definition: "(NASI) Meaning: (pp.) Noun , cooked rice. M a, neutral. Canasian, one cooking."},
    {word: "ngeni", definition: "(NĞENI) Meaning: (pp.) Adverb of time, now. Nğeninan, now at this very moment; nğening gatpanapun, this afternoon, or, nğening bengi, tonight, etc."},
	{word: "ngisi", definition: "(NĞISI) Meaning: (pp.) Facial gestures in general, like the false smiles of the sangleyes (chinamen), or, grimace of a child about to cry, o f the dog about to bite. Neutral verb, future,, and its infinitive , Nğumisi, to grimace. P. 3. Nğisian, at whom he is grimacing with a false smile , and with annoyance . Nğisinğisi, and Mi, frequentative."},
	{word: "ognay", definition: "(OGNAY) Meaning: (dipht.) Active verb, ivosnav. and its infinitive, manosnav. to augment a thing that cannot reach up to, like a rope, or a cloth. P. 1. that which is added to, the ingredient part. P. 3. that which is augmented, the recipient part. See Dugtung, Suglung."},
	{word: "ogto", definition: "(OGTO) Meaning: (pp.) Ogtong aldao, or, caugtuan aldao, midday, noon; variation: to work/ make a thing until midday, to stay until / be overtaken by midday, v. g. Manugtu na can aldao caque queti, come here about noon / by midday you should arrive here. P. 3. what is done at that time (midday); Maogto, meogto, to eat lunch at 2 o’clock, after midday. P. 3. Paugtuan, peugtoan, that which, like lunch, or merienda, afternoon snacks."},
	{word: "onyat", definition: "(ONYAT) Meaning: (pp.) Active verb, munvat, and its infinitive, manonvat. to unfold by stretching out a string, or wire. P. 1. and P. 2. that which is stretched; the construction is also intransitive: an animal stretching out its body, like what cats and dogs do. And also, man, when he awakens, stretches his arms, or shakes his legs. To one who wields a whip: Yunyat mu, extend your arm more, to give it a greater force. Unyatunyat, and I, frequentative."},
	{word: "ognas", definition: "(OGNAS) Meaning: (pp.) Active verb, ivosnas. and its infinitive, manosnas. to lower, like the sail. P. 1. the sail. Neutral verb and that of Mi, to decrease, or wane, like the tide, or the strength of a man growing old, or the price of goods being sold. Ica and Maca. Panugnas daca pagao, I shall massage your shoulders. Yugnas da ca buntoc, etc."},
	{word: "oyag", definition: "(OYAG) Meaning: (a.) Adjective, indicative sign, symptom, v. g. a small pimple, if seen by a physician, he will say, this is an abscess, or a boil, or smallpox; from this: Alan oyag nang súmala, alang oyag nang datang nitang tauo, there is no indication of dawn; there is no indication that that man would be coming; a variation: of a child manifesting signs of becoming great someday, they say: Maqui oyag yang malyarin tauo, the boy shows signs that he shall turn out to be a great man, or a big man. See A lug, that it is not a thing that could be seen as the oyag."},
	{word: "ouay", definition: "(OUAY) Meaning: (pp.) Ouay maqui balay, from the house and from its owner."},
    {word: "oua", definition: "(OUA) Meaning: (pc.) Adverb of assent, yes. Pa oua, to say yes. P. 3. to whom."},
    {word: "ouay", definition: "(AWA) Meaning: (pc.) Adverb of assent, yes. Pa oua, to say yes. P. 3. to whom."},
	{word: "pacnit", definition: "(PACNIT) Meaning: (pp.) Adjective, flayed,or detached, disjoined. Active verb, macnit. ipacnit. and its infinitive, mamacnit. to detach, or to fleece. P. 2. that which is detached. Ma, neutral."},
	{word: "payacpac", definition: "(PAYACPAC )Meaning: Payacpac, mayacpac, and its infinitive, to flap the wings, like a bird flapping its wings in flying, or a rooster flapping its wings before crowing. Payacpacan and Mi, with an, what is affected by the flapping of the wings.."},
	{word: "palad", definition: "(PALAD)Meaning:  (p p .) Noun , the palm of the hand. Neutral verb , past, Melad, and the at of Mi, to extend the palm of the hand .P.1. past. Melad, the palm . Also , idiomatically , blessedness, good fortune! Mipalad, or, micapalad, to find happiness, find good fortune . Ica and maca. Mapalad , adjective. Capolaran, abstract. Variations: Manimalad, menimalad, to tell the fortune by reading the palms, like the gypsy women do. P.3. to whom"},
	{word: "pagal", definition: "(PAGAL)Meaning: Weariness, fatigue. Past, Megal, to become weary/tired. Ma, become weary, the sim p le p re s e n t is se ld o m u se d ; the v a r i a t i o n is a c t i v e , Pamagalan , pemagalan, the weary in g th in g s done. P.1. Simple past, Pegal, that with which , like a burden. Pagalan, pegalan, to whom . Ma, neutral, lca and Maca, capagalan, quepagalan, that which one gets weary / tired of. Pagal pauas, sweat and labor, like the poor day -laborer. Macapagal, within ten t. P. 3. On what one gets tired of"},
	{word: "pacday", definition: "(PACDAY)Meaning: (dipht.) It is said of the traits of the seed, from which it is known if it will turn out good, or bad, like the grains of palay. Marauac a pacday, he has bad traits. In the way it is said metaphorically of a boy, Anac ya pa ing dutung, balu ta neng lumabung. The tree, while yet a seedling, we know it could grow into a verdant and sturdy one. Also, an active verb and its infinitive, to scare away, like a hunter scaring away the birds, or negritoes on the ambush, when they scream, or when one of them carelessly gives them away by giving out a shout. Pacdayan, pecdayan, P. 2. at whom. Ma, neutral, become scared. Pipacdayan, the scary place, like between Garlit and San Miguel, where ambuscades often occur. Mipacday, like mipaticdao; micapacday, like micapaticdao."},
	{word: "quilabut", definition: "(QILABUT)Meaning: .(pp.) The raising of hairs, ortingling sensation/goose pimples on theskin becuase of suddden fear, or sudden	cold. Verbal, mansilabut, the feeling of sudden fear, or horror. Quilabutan, adjective. 3. the objective /motive. Maca,	causal."},
	{word: "quilip", definition: "(QUILIP)Meaning: (pp.) Noun, glare, sparkle, like of	glass upon turning it under the light of the sun, the glare, or sparkle it produces in this manner. Neutral verb and its	frequentative, quilapquilap, to glisten, to	gleam: mirror, spectacles, spangles."},
	{word: "quitil", definition: "(QUITIL)Meaning: .(a ) Quitilquitil, to act imperfectly, v.g. the fish that bites the bait a little, once	or twice , but does not swallo wit; those who fastidiously put the handon the plate, and take almost nothing; one who has	something to say, or is about to peak, but	hesitates: is quitilquitil ya dila, and its	neutral of Mi. P. 2. that which, like the	bait, etc"},
	{word: "quintal	", definition: "(QUINTAL)Meaning: (pp.) Noun, hot iron used for	marking, or branding animals, or slaves. Active verb, future, Cumintal, and its	infinitive, mansintal. to mark thus. P. 1.	that with which. P. 2. past, Quinintalan, on which , on whom. Mi, transitive; Mi,	passive. M i, with an."},
	{word: "quitquit", definition: "(QUITQUIT)Meaning: (pp.) Adjective, said of one who	can hardly open the eyes, either, because of the slimy moisture running from the	eyes, or for being very fat, like a pig, who	is Macaquitquitya mata"},
	{word: "salabas", definition: "(SALABAS)Meaning: (pp.) Noun, wind blowing from the northeast"},
	{word: "sabil", definition: "(SABIL)Meaning: (pp) Neutral verb and that of Mi, bedragged on the ground , like a habit, or a student’s uniform , worn the wrong way, or badly put on. P.1. and its frequentative, sabil sabil. that which is made to drag on the ground . The same is pasabel, rather than pasabilan. Variation : active , to drag  the cloth. Maca, being dragged along. Sabil Sabil, and Mi, frequentative"},
	{word: "sacup", definition: "(SACUP)Meaning: (pp.) Adjective, a subject, like a vassal, or an inferior, or the territory of a certain jurisdiction. Active verb and its infinitive, manvacup. to have authority, or jurisdiction. And also to reduce to vassalage those who used to be independent by subduing them. P. 1. the cause, or motive. P. 2. past, Secupan, those under one’s jurisdiction, dominion, or protection. Ma, neutral, lea and Afaca, like indebtedness."},
	{word: "sadsad", definition: "(SADSAD)Meaning: (pp.) Adjective, a thing that is already at, or has arrived at its destination, its end, its peak, its perfection, like sacdal, sadsad ya cabanalan, or, sadsad ya camulangan. Neutral verb and its infinitive, manvadsad, to arrive at the port, or wharf, landing place , dock, principally at the desired port, which is the destination. P. 1. the ship , o r through the e m e a n s thereof. P. 3. th e d o c k s/port, o r dungan. Idiomatically to arrive at the purpose of a business, like to be married effectively. P. 1. the business, affair, or contract. M i, transitive; Mi, p assiv e; also in both senses and its frequentitive , pasadsadsadsad, v. g. Epaiuad pasadsadsadsad netang camulangana. It is not only occasional that he is foolish. He is foolish all the time."},
	{word: "taba", definition: "(TABA)Meaning: (a.) Noun , fat, grease. Neutral verb, fu tu re , taba, and that of Ma, to become fat, or increased, like the flood, o r the tide. Mataba, adjective , fat. Ica, and Maca, the cause; Mangataba, and micataba, plurals.Cataban, abstract , fatness like casampatan."},
	{word: "tab-blan", definition: "(TAB-BLAN)Meaning: (cor.) Mitab-blan, become affected, like, by the wind. Ica, and Maca."},
	{word: "tabun", definition: "(TABUN)Meaning: (pp.) Noun, a dam, dike, enbankment of a river. Active and its infinitive, manabun. to build, or make a dam. P. 1. that with which, like the materials. P. 3. past, Tibunan, the river, or that which obstructs, the materials, or the people who are obstructed by a closed door, or gate, or merchandise that is put on embargo,	according to its kind, and cannot be passed, or allowed to be sold: all these cannot pass, so they are, Macatabun. be dammed, or be on hold. Mi, with an, mitabunan. and its manga."},
	{word: "tacap", definition: "(TACAP)Meaning: (a.) Adjective , covering , lik e th a t o f jar. Covered. Active verb, future , Tacap, and its infinitive , manacap. to cover, to put the lid on. P. 1. ,past, Tecap, that with which . P. 3. past, Ticpan, that which was covered . Mi, transitive ; Mi, passive. Mi, with an, and its manga. Panacap daco, says a baintauo w h e n h e is m a d e to stand for a child fathered by another, that is, they use me as a cover-up , they make e me a cover-up for his sin. And it can be said, tecap , v. g. Papanğasauarecaco, buriracong itacap quing mulang da. They want me to marry her, they want to use m e as coverup for their foolishness/ mistake. Mitacpanan, is said o f those who c o v e r u p in this manner: I let you five cavans of palay, so that in the coming harvest will h a v e to give me ten cavan s, a n d that will erase /coverup the five you owe me. Neutral verb and its infinitive, one who is covering/obstructing the view , or the light, with an. P.3. the thing covered from view, or from whom the light is obstructed."},
	{word: "vili", definition: "(VILI)Meaning: (pp.) Mavili, mevili, one who is	attracted , or fascinated, like in seeing a	garden, well groomed and elegant. Ica, and	Maca, the cause. P.3. of Ca, the object of	this fascintion, like bags of money to an	avaricious person, or regalias, fineries,	trosseau, to women. Manğavili, menğavili,	and also , mangangavili, either for one or	for many. P. 3. Panğanğavilian, or,	pangauilian, etc. Micavili, with company,	and micauili. verbal. Manavili, active, to	attract, to procure, what in cites pleasure, volutupous. P.3. to whom. Panavilian,	managavili, menagavili, with a thing that	pleases or attracts an other, but it has to be	a gratifying thing. P.1. that with which,	like a loaf of bread, to a child; like green	grass, to a flock. P. 3. that which is	attracted, or ventured to attract in this	manner, because Manavili is to show that	somenthing which another desires, like	alfalfa to the donkey."},	
	{word: "veuay", definition: "(VEUAY)Meaning: (dihthong). Adjective, long, like a	bamboo can e, road. Caveve, a single cane,	a single long road/street. Pabanuans	veuav. the whole year through."},
	{word: "vala", definition: "(VALA)Meaning:  (pp.) Active verb, future, Yumala, or,	umala, and its infinitive, manvala. the ship	departing from the shore, like to go to a	deep bay, or to begin its voyage to sea, including, to swerve away, or to change	course in general. P. 1. that which. Maca,	it is swerving. Also, neutral verb and that	of Mi, to swerve, to make a turn, or to	move away. Ma, with intensity. Ma, in	abundance, valavala, restless."},
	{word: "valac", definition: "(VALAC)Meaning: (a.) Active verb and its	infinitivejnanvalac. to mangle, or break	into pieces with anger and fury. P. 1. that	which is destroyed in this manner, breaking	it into pieces. Mi, transitive; Mi, passive	and its manga. Ma, in abundance."},
	{word: "vanan", definition: "(VANAN)Meaning: (a.) Adjective, all that is on the	righthand side. Neutral verb and that of	Mi, become placed on the right-hand side.	P. l.past, Venan, that whichis placed on	the right-hand side. Maca, is on the righthand side. Pauanan, like a book, read from	left to right. Pauananan, see to it that it is	placed on the right-hand side. Vanan, caili,	to the right, to the left"},
	{word: "ubac", definition: "(UBAC)Meaning: (pp.) Noun, the bark of a tree, or that	of a banana, which like a shirt, remove	one out and another remains, down to	many more. Active verb and its infinitive,	manubac. to strip the bark in this manner.	P. 2. that which. Piubacan, the remainders,	even that of flayed animals. See Sabac,	Sapua."},
	{word: "ubi", definition: "(UBI)Meaning: (pp.) Noun, a species of root crop.	Manubi, to plant them"},
	{word: "ugali", definition: "(UGALI)Meaning: (p p .) Adjective, custom, deep-seated habit. Custom usage , it is said of an ordinary thing , not so good, not so bad. Mi, neutral , become accustomed. Miugalina, it has become the custom. Maquiugali, to accommodate to the custom, Dum Romee fu eris, When in Rome , do as the Romans do. Paquiugalian, the thing to which you get accustomed Maca, to be in vogue, according to the prevailin g custom."},
	{word: "uiab", definition: "(UIAB)Meaning:(Uvab) (pp.) Noun, yawn, due to	sleepiness, or due to hunger. Neutral verb,	muiab. manuiab. to yawn . Uiabuiab,	frequentative"},
	{word: "ula", definition: "(ULA)Meaning: (pp.) Noun, or nament, finery,	accomplishment. Maula, in abundance.	Magcaula, with intent. P.1. Yula, & or,	Pagcaula, that with which; active form:	Managaula, to adorn, like an image. P.1.	Ipanagaula, that with which. P.3. to	whom, like a little angel, or palm on Palm	Sunday. Amanunmaula, great saving."},
	
];  

const form = document.getElementById("search-form");
const input = document.getElementById("search-input");
const results = document.getElementById("results");

form.addEventListener("submit", function(event) {
	event.preventDefault();
	const searchTerm = input.value.toLowerCase();
	const filteredData = data.filter(function(item) {
		return item.word.includes(searchTerm);
	});
	if (filteredData.length > 0) {
		results.innerHTML = "";
		filteredData.forEach(function(item) {
			const wordDiv = document.createElement("div");
			const definitionDiv = document.createElement("div");
			wordDiv.innerText = item.word;
			definitionDiv.innerText = item.definition;
			results.appendChild(wordDiv);
			results.appendChild(definitionDiv);
		});
	} else {
		results.innerHTML = "<p>No results found.</p>";
	}
});
